services:
  s_api_auth1:
    container_name: c_auth_api_1
    image: mirze1993/auth-api:B${BUILD_NUMBER}
    restart: unless-stopped
    deploy:
      resources:
        limits:         
          memory: 256M
        reservations:         
          memory: 128M
    networks:
      - net_backend
      - shared-web
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://localhost:80/swagger/index.html || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SERVICE_NAME: ${AppName}
      openTelemetry__OtlpTracingEndpointKey: ${GRAFANA_BASIC_AUTH_PASSWORD}
      openTelemetry__OtlpMetricsEndpointKey: ${GRAFANA_BASIC_AUTH_PASSWORD}
      PYROSCOPE_APPLICATION_NAME: ${AppName}
      PYROSCOPE_PROFILING_ENABLED: "1"
      CORECLR_ENABLE_PROFILING: "1"
      CORECLR_PROFILER: "{BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}"
      CORECLR_PROFILER_PATH: "/app/Pyroscope.Profiler.Native.so"
      LD_PRELOAD: "/app/Pyroscope.Linux.ApiWrapper.x64.so"
      
      PYROSCOPE_SERVER_ADDRESS: "https://profiles-prod-021.grafana.net"
      PYROSCOPE_BASIC_AUTH_USER: ${grafana_user}
      PYROSCOPE_BASIC_AUTH_PASSWORD: ${PYROSCOPE_BASIC_AUTH_PASSWORD}
      
      DOTNET_EnableDiagnostics: "1"
      DOTNET_EnableDiagnostics_IPC: "0"
      DOTNET_EnableDiagnostics_Debugger: "0"
      DOTNET_EnableDiagnostics_Profiler: "1"
      
      PYROSCOPE_PROFILING_ALLOCATION_ENABLED: "true"
      PYROSCOPE_PROFILING_CONTENTION_ENABLED: "true"
      PYROSCOPE_PROFILING_EXCEPTION_ENABLED: "true"
  
  s_api_auth2:
    container_name: c_auth_api_2
    image: mirze1993/auth-api:B${BUILD_NUMBER}
    restart: unless-stopped
    deploy:
      resources:
        limits:        
          memory: 256M
        reservations:         
          memory: 128M
    networks:
      - net_backend
      - shared-web
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://localhost:80/swagger/index.html || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SERVICE_NAME: ${AppName}
      openTelemetry__OtlpTracingEndpointKey: ${GRAFANA_BASIC_AUTH_PASSWORD}
      openTelemetry__OtlpMetricsEndpointKey: ${GRAFANA_BASIC_AUTH_PASSWORD}
      PYROSCOPE_APPLICATION_NAME: ${AppName}
      PYROSCOPE_PROFILING_ENABLED: "1"
      CORECLR_ENABLE_PROFILING: "1"
      CORECLR_PROFILER: "{BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}"
      CORECLR_PROFILER_PATH: "/app/Pyroscope.Profiler.Native.so"
      LD_PRELOAD: "/app/Pyroscope.Linux.ApiWrapper.x64.so"

      PYROSCOPE_SERVER_ADDRESS: "https://profiles-prod-021.grafana.net"
      PYROSCOPE_BASIC_AUTH_USER: ${grafana_user}
      PYROSCOPE_BASIC_AUTH_PASSWORD: ${GRAFANA_BASIC_AUTH_PASSWORD}

      DOTNET_EnableDiagnostics: "1"
      DOTNET_EnableDiagnostics_IPC: "0"
      DOTNET_EnableDiagnostics_Debugger: "0"
      DOTNET_EnableDiagnostics_Profiler: "1"

      PYROSCOPE_PROFILING_ALLOCATION_ENABLED: "true"
      PYROSCOPE_PROFILING_CONTENTION_ENABLED: "true"
      PYROSCOPE_PROFILING_EXCEPTION_ENABLED: "true"

networks:
  net_backend:
    driver: bridge
  shared-web:
    external: true