services:
  s_api_auth1:
    container_name: c_auth_api_1
    image: mirze1993/auth-api:B${BUILD_NUMBER}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - net_backend
      - shared-web
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://localhost:5197/swagger/index.html || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  s_api_auth2:
    container_name: c_auth_api_2
    image: mirze1993/auth-api:B${BUILD_NUMBER}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - net_backend
      - shared-web
    expose:
      - "80"
    healthcheck:
      test: curl -sS http://localhost:80/swagger/index.html || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  net_backend:
    driver: bridge
  shared-web:
    external: true