name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Presentation/AuthApi/**'   
  pull_request:
    branches: [ main ]
    paths:
      - 'Presentation/AuthApi/**' 

jobs:
 docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Presentation/AuthApi/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/tempauthapi:latest, ${{ vars.DOCKERHUB_USERNAME }}/tempauthapi:${{ github.run_number }}
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_USERNAME }}/tempauthapi:latest
          cache-to: type=inline
      - 
        name: Deploy to Contabo Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/tempauthapi:latest
            docker stop c_auth_api || true
            docker rm c_auth_api || true
            docker compose -f /root/docker-files/backend/docker-compose.yml up -d

            
